@startuml


class WeatherService{
    - analizadores : Analizador[]

    ' analiza para cada lugar, su clima.
    + analizarClimas() : void
    - guardarClima(clima) : void
}

' tiene los lugares y a quien alarmar
class Analizador{

    - lugares : Lugar
    - alertadores : Alertador[]
    - criterios : CriterioAlarma[]
    ' analiza si es alarmante el clima, dispara las alarmas
    + analizarClima(Clima clima) : void
}

WeatherService --> Analizador

Analizador --> Alertador
Analizador --> CriterioAlarma

Interface CriterioAlarma{
    + esAlarmante(Clima clima) : bool
}

Class CriterioMayorTemperaturaHumedad implements CriterioAlarma{
    - temperaturaAlarmante : Double
    - humedadAlarmante : Double
    + esAlarmante(clima) : Bool
}

WeatherService --> WeatherApiClient

class WeatherApiClient{
    obtenerClima(String lugar)

}

class AnalizadorClima{
    - climaEsAlerta(clima: Clima) : bool
}

WeatherService --> AnalizadorClima

interface Alertador{
- enviarAlerta()
}

class AlertadorMail implements Alertador {
- mail : String
- mailDestino : String
- enviarAlerta()
}
AlertadorMail --> MailService
' manda los mails
class MailService{
- provider?
- enviarMail(direccion: string, contenido : String)
}


@enduml