@startuml


class WeatherService{
    - analizadores : Analizador[]

    ' analiza para cada analizador, su climas
    + analizarClimas() : void
    - guardarClima(clima) : void
}

' tiene los lugares y a quien alarmar
class Analizador{

    - nombreLugar : String
    - suscriptores : Suscriptor[]
    ' le pasa a todos los suscriptores el clima, y cada suscriptor evalua con SUS criterios y hace SUS alarmas
    + reportarClima(Clima clima) : void
}

Analizador --> Suscriptor
Class Suscriptor{
    criterios : CriterioAlarma[]
    alertadores : Alertador[]

    + notificarClima(Clima clima)
    - analizarClima(Clima clima)
    - cumpleCriterios(Clima clima) : bool
    - alertar(Clima clima) : void
}


WeatherService --> Analizador

Suscriptor --> Alertador
Suscriptor --> CriterioAlarma

Interface CriterioAlarma{

    + esAlarmante(Clima clima) : bool
    + mensajeAlarma(Clima clima) : String
}

Class CriterioMayorTemperaturaHumedad implements CriterioAlarma{
    - temperaturaAlarmante : Double
    - humedadAlarmante : Double
    + esAlarmante(Clima clima) : Bool
    + mensajeAlarma(Clima clima) : String
}

WeatherService --> WeatherApiClient

class WeatherApiClient{
    obtenerClima(String lugar)

}

interface Alertador{
+ enviarAlerta(String mensaje)
}

class AlertadorMail implements Alertador {
- mailService : MailService
- mail : String
- mailDestino : String
+ enviarAlerta(String mensaje)
}
AlertadorMail --> MailService
' manda los mails
class MailService{
- provider?
- enviarMail(direccion: string, contenido : String)
}


@enduml